require'plugin-settings.airline'
require'plugin-settings.bracey'
require'plugin-settings.coc-nvim'
require'plugin-settings.dashboard'
require'plugin-settings.easymotion'
require'plugin-settings.floaterm'
require'plugin-settings.fugitive'
require'plugin-settings.fzf'
require'plugin-settings.git-gutter'
require'plugin-settings.indentLine'
--require'plugin-settings.lspsaga'
require'plugin-settings.mundo'
require'plugin-settings.NERDCommenter'
require'plugin-settings.NERDTree'
--require'plugin-settings.nvim-lsp'
--require'plugin-settings.nvim-completion'
require'plugin-settings.nvim-treesitter'
require'plugin-settings.signit'
--require'plugin-settings.startify' -- broken
require'plugin-settings.vimspector'
require'plugin-settings.vimtex'
--require'plugin-settings.vimwiki' -- broken too
