--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/data/Wallpapers/Kimetsu_no_yaiba_01.jpg"

-- Special
background="#1b1918"
foreground="#a8a19f"
cursor="#a8a19f"

-- Colors
color0="#1b1918"
color1="#f22c40"
color2="#7b9726"
color3="#c38418"
color4="#407ee7"
color5="#6666ea"
color6="#3d97b8"
color7="#a8a19f"
color8="#766e6b"
color9="#f22c40"
color10="#7b9726"
color11="#c38418"
color12="#407ee7"
color13="#6666ea"
color14="#3d97b8"
color15="#f1efee"
