#! /bin/sh

sxhkd &
xrdb $HOME/.Xresources
~/.fehbg
wal -R
dunst &
pasystray &
optimus-manager-qt &
udiskie &
$HOME/script/polybar/start_pb.sh
$HOME/script/start_picom.sh
$HOME/script/idleLock.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		3
bspc config window_gap			3

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Steam state=floating
bspc rule -a line.exe state=floating
bspc rule -a scrcpy state=floating
